### ISSUE TITLE
Pistons and forge.stone is still limited when removed upon config reload

### ISSUE THREAD

**Issue by Venitryx** [VecooDEV/ChunkLimiter#1]
Hello, I really like the concept of this mod. However, pistons and the block tag 'forge.stone' is still being limited when I change them and reload the config file. But, adding and removing *other* blocks and block tags (and their amounts) work as expected.

**Comment by VecooDEV** [comment]
Hello, I am busy with other projects at the moment, I will fix it when I have a chance, but overall I am not sure that there is a bug. Expect it within two weeks.

**Comment by VecooDEV** [comment]
Fix release 1.2.0.
